def estrofe(n):
    print(f'{n} patinhos')
    print(f'Foram passear')
    print(f'Além das montanhas')
    print(f'Para brincar')
    print(f'A mamãe gritou')
    print(f'Quá, quá, quá, quá!')
    print(f'Mas só {n - 1} patinhos')
    print(f'Voltaram de lá')
    print(f'Agora só falta aprender a fazer loop!')
